server:
  port: 8001

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 20
  application:
    name: shop-sms


sms.register : queue-register